DB_INSTANCE = "project-586e4c98-e32a-46da-b1c:us-central1:github-repo-analyzer"
DB_DRIVER = "pymysql"
DB_USER = "root"
DB_PASSWORD = "gitrEpoadmin@2"
DB_NAME = "github_repo_analyzer"
GITHUB_TOKEN = "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"